version: "3.9"

services:
  autodashboard:
    image: autodashboard/autodashboard:latest
    ports:
      - "80:80"

  autodashboard-backend:
    build: .
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
